### ISSUE TITLE
Intune MAM SDK with Couchbase.Lite.Storage.SQLCipher (linker errors)

### ISSUE THREAD

**Issue by alexrainman** [msintuneappsdk/intune-app-sdk-xamarin#18]
I get linker errors when I try to use Intune MAM SDK with Couchbase.Lite.Storage.SQLCipher:

```
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_sqlite3_vfs_unregister'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/me/Projects/LDAP/iOS/obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.1/mtouch-cache/libIntuneMAM.a(SQLiteHooks.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/me/Projects/LDAP/iOS/obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.1/mtouch-cache/libsqlcipher.a(sqlite3.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_sqlite3_vfs_register'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/me/Projects/LDAP/iOS/obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.1/mtouch-cache/libIntuneMAM.a(SQLiteHooks.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/me/Projects/LDAP/iOS/obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.1/mtouch-cache/libsqlcipher.a(sqlite3.o) (Location related to previous error)
error MT5209 : Native linking error : 2 duplicate symbols for architecture x86_64
MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/me/Projects/LDAP/iOS/obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.1/Entitlements.xcent
MTOUCH : error MT5202: Native linking failed. Please review the build log.
```

Any ideas?

**Comment by Kyle-Reis** [comment]
@alexrainman, it looks like both static libraries hook the sqlite3_vfs_register() and sqlite3_vfs_unregister() methods, leading to a symbol conflict. We can (and will) make a change on our end to avoid this conflict, but it might take some time to get the release out as we'll need to run a full test pass before that can happen. One way you could potentially work around this would be to use our [app wrapper](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios) instead of the Xamarin SDK bindings for this app. The app wrapper will inject our dynamic framework, rather than the static library which should avoid this symbol conflict. Does your app need to call any of our APIs?

**Comment by alexrainman** [comment]
Using the app wrapper is not an option for us. I contact you guys this way because it is faster but, I work for Schlumberger and we will be soon the biggest customer MSFT will have on Intune.

We are counting on your help, as always.

**Comment by alexrainman** [comment]
We switched to Couchbase.Lite.ForestDB storage engine for now as a workaround but, we will love to have a hot fix from you guys. Thanks

**Comment by Kyle-Reis** [comment]
We’ve already made the fix on our end. It should be available in an upcoming release.

**Comment by alexrainman** [comment]
That's awesome. Thanks

**Comment by Kyle-Reis** [comment]
Hey @alexrainman, sorry, I just noticed your last comment. The fix should be available in [today's release](https://www.nuget.org/packages/Microsoft.Intune.MAM.Xamarin.iOS/) (10.0.7)

**Comment by alexrainman** [comment]
This is fixed now. Thanks
