### ISSUE TITLE
DeRegisterAndUnenrollAccount does not remove account

### ISSUE THREAD

**Issue by Knots23** [msintuneappsdk/intune-app-sdk-xamarin#32]
**Describe the bug:**
The first time you call `IntuneMAMEnrollmentManager.Instance.LoginAndEnrollAccount(null);`, the Microsoft login page is shown, as is expected. Once signed in, you can sign out using the `IntuneMAMEnrollmentManager.Instance.DeRegisterAndUnenrollAccount(IntuneMAMEnrollmentManager.Instance.EnrolledAccount, true);`. All values the can be found in the IntuneMAMEnrollmentManager.Instance are indeed set to null and a wipe is performed.
When starting the app again, the `IntuneMAMEnrollmentManager.Instance.LoginAndEnrollAccount(null);` is called again, but this time, no login page is shown. Instead, the user is logged in automatically using the previously used credentials.

**Expected behavior:**
When calling the `IntuneMAMEnrollmentManager.Instance.LoginAndEnrollAccount(null);`, the login page is always shown and - since null is provided - no account is used automatically.

**Smartphone (please complete the following information):**
 - Device: iPhone 6 Plus
 - OS: iOS 12.3.1

**Intune App SDK Xamarin Bindings:**
- Microsoft.Intune.MAM.Xamarin.iOS version 10.0.7

**Comment by Kyle-Reis** [comment]
Hey @Knots23, this behavior is by design, as the Intune SDK does not clear the ADAL token cache by default. This is because the publisher's apps could be leveraging single-sign-on, and we do not know if there are other apps from the same publisher utilizing the shared ADAL cache. However, if all the apps from a given publisher are uninstalled, a call to LoginAndEnrollAccount should prompt for credentials upon the first reinstall of any app. If you do prefer that the user be signed out of all the apps that may be sharing the token cache when the user signs out of any single one, you can use the ADAL APIs to clear the token cache directly from the enrollment delegate's UnenrollRequestWithStatus method, which should get invoked after calling DeRegisterAndUnenrollAccount

**Comment by chknabeel** [comment]
I have integrated Intune with MSAL in swiftui app. Login is working fine but I am not sure how to create a logout behavior?
How to clear token cache when using MSAL with Intune instead of ADAL? 
I tried to use `applicationContext.getCurrentAccount` but it is returning `nil`. @Kyle-Reis  can help. 
Thanks
