### ISSUE TITLE
Microsoft.Intune.MAM.Xamarin.Android support to Androidx

### ISSUE THREAD

**Issue by ArunaVignesh** [msintuneappsdk/intune-app-sdk-xamarin#44]
Hi,

I have created  the Xamarin.Forms application with intune support. Xamarin.Forms supports Android X, but it does not work because Microsoft.Intune.MAM.Xamarin.Android is not supported. This is causing problems for our products. Please tell when this will be done. Microsoft.Intune.MAM.Xamarin.Android (3.0.4635.1) released on  December 17, 2019 . there is no updation for nearly 7 months and above. Please help to resolve.

**Comment by TrueGeek** [comment]
This is causing serious problems for us as well. 

Adding the Microsoft.Intune.MAM.Xamarin.Android NuGet package fails with the latest version of Xamarin.Forms

```
Version conflict detected for Xamarin.Android.Support.v7.RecyclerView. Install/reference Xamarin.Android.Support.v7.RecyclerView 28.0.0.3 directly to project AgentApp.Android to resolve this issue. 
 AgentApp.Android -> Xamarin.Forms 4.8.0.1269 -> Xamarin.Android.Support.Design 28.0.0.3 -> Xamarin.Android.Support.v7.RecyclerView (= 28.0.0.3) 
 AgentApp.Android -> Microsoft.Intune.MAM.Xamarin.Android 3.0.4635.1 -> Xamarin.Android.Support.v17.Leanback 28.0.0.1 -> Xamarin.Android.Support.v7.RecyclerView (= 28.0.0.1).

```

Adding the Android.Support packages manually, as suggested by NuGet, prevents the project from building with multiple errors of "Invalid Android Support Library Configuration".

The iOS NuGet package was updated 2 months ago and can be added without error. Can we get an updated Android package, please? It's very hard to explain to enterprise customers that we can't support Microsoft's Intune platform because we're using Microsoft's Xamarin framework.

**Comment by Kyle-Reis** [comment]
Assigning this to @cofitz1 and @meghandaly.

**Comment by meghandaly** [comment]
Apologies for the radio silence, our next release will include updated references to the latest support libraries and we are targeting it before years end.

We are actively reevaluating our Xamarin support and are working to better address issues in the future and we thank you for your patience.

**Comment by NicholasNgN3Y** [comment]
Good day, @meghandaly, 
I am facing the same issue on this. would like to enquire if there is any timeline that I can use to report to clients.

Using the sample [Xamarin Forms - Android app](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps/tree/master/TaskrForms), 
upon upgrading it to latest Xamarin.Forms > 4.5 
the landing page just hits a white page like described [here].(https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps/issues/11)

I believe it is due to the build auto migrating to Android X during the build process, 
I see that the Intune Android SDK guide mentions that the Remapper doesn't support Android X? 

Seems like I'm stuck for the time being. 

Appreciate the awesome job you all are doing!

**Comment by NicholasNgN3Y** [comment]
Are we able to raise a support case for this?

**Comment by JamestsaiTW** [comment]
Is there any update news?

**Comment by ArunaVignesh** [comment]
@meghandaly, Is there any update regarding the release?

**Comment by JamestsaiTW** [comment]
@meghandaly, Is there any update news?

**Comment by OleksandrMovchan** [comment]
@meghandaly We still blocked by this issue. Do you have any roadmap for Xamarin.Android version?

**Comment by paulvwarner** [comment]
@meghandaly I'm blocked by this as well. Is there any news about this?

**Comment by Dimdron** [comment]
hey @meghandaly, could you share any information regarding updating MAM Binding for Android?

**Comment by JamestsaiTW** [comment]
@meghandaly,  Is there any update news?

**Comment by meghandaly** [comment]
No update at this time.

**Comment by JamestsaiTW** [comment]
@meghandaly, After more than two months, is there any update news?

**Comment by JamestsaiTW** [comment]
> No update at this time.
@meghandaly, After more than two months, is there any update news?

**Comment by hernandoz** [comment]
@meghandaly, Is there any update news?

**Comment by rdieske** [comment]
@meghandaly, Bump... Any update news ?

**Comment by Aniiia** [comment]
Hi,

any updates on this?

Greetings

**Comment by Mileshdpatel** [comment]
@meghandaly, as per support case: 30659658 and escalation case: 11137614 we are also having this issue.

**Comment by JamestsaiTW** [comment]
As this following link from Microsoft documents:
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin

![image](https://user-images.githubusercontent.com/9651229/200630839-f3907927-aa86-4a86-be56-b9ea0d986e33.png)
So, this problem will be solved at Q2CY2023?

Oh...BTW, today is 11/9/2022. 😏

**Comment by ihariza** [comment]
Hi, 
'm blocked by this issue as well. I've done a Xamarin Android Binding  with the last release, but I can't use it because MAM components extends from App, and my app uses androidx library components. Is there any way to implement this without making a plugin to rewriting classes?

Greetings.

**Comment by monkeychew-ico** [comment]
@ihariza I found this third-party library equivalent, hope it helps. It supports Xamarin Android 13.

https://www.nuget.org/packages?q=Beezy.Intune.Android.Bindings

**Comment by meghandaly** [comment]
There is no future development planned for supporting newer Android OS targeting for Xamarin.Android and Xamarin.Forms.

For apps that target Android 10.0+, please [upgrade your existing apps to .NET MAUI](https://learn.microsoft.com/dotnet/maui/migration/?view=net-maui-7.0) and leverage the [Microsoft.Intune.Maui.Essentials.android](https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/) NuGet package to enable data protection features and mobile app management.

**Comment by leoslima13** [comment]
> There is no future development planned for supporting newer Android OS targeting for Xamarin.Android and Xamarin.Forms.
> 
> For apps that target Android 10.0+, please [upgrade your existing apps to .NET MAUI](https://learn.microsoft.com/dotnet/maui/migration/?view=net-maui-7.0) and leverage the [Microsoft.Intune.Maui.Essentials.android](https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/) NuGet package to enable data protection features and mobile app management.

@meghandaly but what about an application for Xamarin Forms? i want to migrate it to .net maui but there's no package for iOS just for android, and I can't stay on XF because doesn't have compatible package for Android, so I'm behind the eight ball, there`s a previews package for .net MAUI working on both iOS and Android?
