### ISSUE TITLE
Known Issue: Blank screen on launch of Android LOB apps using Intune App SDK Xamarin Bindings

### ISSUE THREAD

**Issue by mayganm** [msintuneappsdk/intune-app-sdk-xamarin#49]
There's a known issue when launching Android line-of-business (LOB) apps that are using the Intune App SDK Xamarin Bindings, where the app will fail to load and only display a blank screen. This prevents app protection policies (APP, also known as MAM) for LOB apps from syncing with Android devices. Additionally, Microsoft does not currently support the Conditional Access grant “Require app protection policies” with Xamarin apps.

App protection policies for Android apps built with Xamarin will not sync to the device. There is no current workaround for this issue, our engineering team will plan to address this issue in a future release of the Intune App SDK Xamarin Bindings. If you are running into this issue, you can get unblocked by rolling back the app deployment to target Android 9 or using native Android apps not built with .NET.

**Recommendation:** Integrate the Intune App SDK for Android with native Android apps not built with .NET.

**Comment by michaelb-yambay** [comment]
Hi there, I was wondering if I could ask for more detail on the symptoms of issue?

In preparation to attempt integration with InTune into a business application, I've got a basic Xamarin Forms test application that has added the InTune SDK and InTune Xamarin re-mapper nugets:
- An Application class (inheriting from MAMApplication has been added), and overrides the OnMAMCreate() method.  This logs that it's been called, and then calls the base method.
- The MainActivity (inheriting from FormsAppCompatActivity) has been changed to add the OnMAMCreate() method.  This logs that it's been called, and then calls the base method.

When the test application runs:
- Application OnMAMCreate() is called (as seen from logging)
- MainActivity OnMAMCreate() is NOT called.
- Application shows a blank white screen

Is what I'm seeing above due to this error?

**Comment by Aniiia** [comment]
Hi,

any updates on this?

Greetings

**Comment by meghandaly** [comment]
There is no future development planned for supporting newer Android OS targeting for Xamarin.Android and Xamarin.Forms.

For apps that target Android 10.0+, please [upgrade your existing apps to .NET MAUI](https://learn.microsoft.com/dotnet/maui/migration/?view=net-maui-7.0) and leverage the [Microsoft.Intune.Maui.Essentials.android](https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/) NuGet package to enable data protection features and mobile app management.
