### ISSUE TITLE
Help with error: the operation couldn’t be completed. (com.microsoft.commonlib.httpconnector error 603)

### ISSUE THREAD

**Issue by miguelweiss** [msintuneappsdk/intune-app-sdk-xamarin#54]
The issue is related with the registering and enrolling account process in an iOS application.

We are working on an iOS Xamarin based application using  iOS 15.3.1 for iPhone. Building with Xcode 13.3, using MSAL authentication with Microsoft.Identity.Client 4.43.1 Nuget package and using the Microsoft.Intune.MAM.Xamarin.iOS 15.3.0.1 Nuget package.

When we call the **IntuneMAMEnrollmentManager.Instance.RegisterAndEnrollAccount(string identity)** for enrolling an account, then in the **public virtual void EnrollmentRequestWithStatus (IntuneMAMEnrollmentStatus status)** method we are capturing an **IntuneMAMEnrollmentStatus** object with the:
1-  "_Error = The operation couldn’t be completed. (com.microsoft.commonlib.httpconnector error 603)_".
2- "_StatusCode = MamEnrollmentStatusEnrollmentEndPointNetworkFailure)_".

Check the below image for details:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/83839889/164722786-effb634d-244d-43ee-b491-538da6a34fcc.png">

In the Entitlements.plist file we have the following:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/83839889/164722914-eaa77f12-0f5c-4c97-943e-5ac8c19c276b.png">

Any ideas what can cause an "_The operation couldn’t be completed. (com.microsoft.commonlib.httpconnector error 603)_" error?

Thank you very much.

**Comment by darosal** [comment]
Hi @miguelweiss, thanks for reaching out! This error message is one that appears for generic http failures when trying to enroll with our MAM service. Does this enrollment failure happen consistently? Does it also happen on a freshly wiped device?

**Comment by miguelweiss** [comment]
Hi @darosal,

The error does happen consistently and it may come and go randomly without the user doing any changes in his device or to the application.  It may affect an application user for several days and then disappear for several days for it to reappear again, etc...

We haven't been able to figure out what it is the root cause.  The only clue we have is the "he operation couldn’t be completed. (com.microsoft.commonlib.httpconnector error 603)" error message.
The other thing we've noticed is that Intune Company Portal is really slow for when we try to download n install an application.

Any idea how we can capture the base http failure?
Is there a way can tell if Intune is the one failing when we try to enroll the user?

**Comment by darosal** [comment]
Hi @miguelweiss,

There might be more information we can take out of our Intune logs. Do you have any place where you call into the `IntuneMAMDiagnosticConsole.DisplayDiagnosticConsole()` method within your app? If you are able to launch the diagnostic console on a device that has been exhibiting these 603 errors, you should be able to follow the prompts to generate an Intune log file.

I'm hoping that we can pull correlation ids from this log file and see if we can involve another team to give us more info on why these enrollments are failing.

Although the log file shouldn't contain any sensitive data, it is best to continue this thread through our support team so that they can work with you to gather that information. Please check https://docs.microsoft.com/en-us/mem/get-support to see instructions on how to open a support case. You will want to select "Intune" from the list of options under "Help and Support" in the endpoint manager.
